const REQUEST_INGREDIENTS = "REQUEST_INGREDIENTS"
const INGREDIENTS_SUCCESS = "INGREDIENTS_SUCCESS"
const INGREDIENTS_FAIL = "INGREDIENTS_FAIL"
const SEND_NEW_INGREDIENT = "SEND_NEW_INGREDIENT"
const NEW_INGREDIENT_SUCCESS = "NEW_INGREDIENT_SUCCESS"
const NEW_INGREDIENT_FAIL = "NEW_INGREDIENT_FAIL"

export {
  REQUEST_INGREDIENTS,
  INGREDIENTS_SUCCESS,
  INGREDIENTS_FAIL,
  SEND_NEW_INGREDIENT,
  NEW_INGREDIENT_SUCCESS,
  NEW_INGREDIENT_FAIL
}