const REQUEST_INGREDIENTS = "REQUEST_INGREDIENTS"
const INGREDIENTS_SUCCESS = "INGREDIENTS_SUCCESS"
const INGREDIENTS_FAIL = "INGREDIENTS_FAIL"

export {
  REQUEST_INGREDIENTS,
  INGREDIENTS_SUCCESS,
  INGREDIENTS_FAIL,
}