const REQUEST_DAYS = "REQUEST_DAYS"
const DAYS_SUCCESS = "DAYS_SUCCESS"
const DAYS_FAIL = "DAYS_FAIL"
const REQUEST_CURRENT_DAY = "REQUEST_CURRENT_DAY"
const CURRENT_DAY_SUCCESS = "CURRENT_DAY_SUCCESS"
const CURRENT_DAY_FAIL = "CURRENT_DAY_FAIL"

export {
  REQUEST_DAYS,
  DAYS_SUCCESS,
  DAYS_FAIL,
  REQUEST_CURRENT_DAY,
  CURRENT_DAY_SUCCESS,
  CURRENT_DAY_FAIL
}