const REQUEST_DAYS = "REQUEST_DAYS"
const DAYS_SUCCESS = "DAYS_SUCCESS"
const DAYS_FAIL = "DAYS_FAIL"
const REQUEST_CURRENT_DAY = "REQUEST_CURRENT_DAY"
const CURRENT_DAY_SUCCESS = "CURRENT_DAY_SUCCESS"
const CURRENT_DAY_FAIL = "CURRENT_DAY_FAIL"
const REQUEST_NEW_DAY = "REQUEST_NEW_DAY"
const NEW_DAY_SUCCESS = "NEW_DAY_SUCCESS"
const NEW_DAY_FAIL = "NEW_DAY_FAIL"
const REQUEST_MEALS = "REQUEST_MEALS"
const MEALS_SUCCESS = "MEALS_SUCCESS"
const MEALS_FAIL = "MEALS_FAIL"

export {
  REQUEST_DAYS,
  DAYS_SUCCESS,
  DAYS_FAIL,
  REQUEST_CURRENT_DAY,
  CURRENT_DAY_SUCCESS,
  CURRENT_DAY_FAIL,
  REQUEST_NEW_DAY,
  NEW_DAY_SUCCESS,
  NEW_DAY_FAIL,
  REQUEST_MEALS,
  MEALS_SUCCESS,
  MEALS_FAIL
}