const REQUEST_RECIPES = "REQUEST_RECIPES"
const RECIPES_SUCCESS = "RECIPES_SUCCESS"
const RECIPES_FAIL = "RECIPES_FAIL"
const REQUEST_CURRENT_RECIPE = "REQUEST_CURRENT_RECIPE"
const CURRENT_RECIPE_SUCCESS = "CURRENT_RECIPE_SUCCESS"
const CURRENT_RECIPE_FAIL = "CURRENT_RECIPE_FAIL"

export {
  REQUEST_RECIPES,
  RECIPES_SUCCESS,
  RECIPES_FAIL,
  REQUEST_CURRENT_RECIPE,
  CURRENT_RECIPE_SUCCESS,
  CURRENT_RECIPE_FAIL
}